### ISSUE TITLE
Consider adding 'Issues Templates' to Repo

### ISSUE THREAD

**Issue by tesla809** [meeshkan/hmt#193]
# Summary

Having issues template will allow for consistent issues from a growing open source community in the future. Having a template can act as a checklist for the person creating the issue so that they consider all the relevant information before submitting. It also formats the issue in a cogent and understandable manner to help the maintainers.

You can copy: 
https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/.github

## Motivation
Why are we doing this? 
Having a template acts as a checklist for the person creating the issue. They will consider all the relevant information before submitting. It will help the contributor think deeper about the problem which will give greater clarity to the issue, bug or feature request. 

What use cases does it support? 
Allows for expanding the open-source community in a sustainable manner.
Allows for developers to write more detailed issues which helps with development.

What is the expected outcome?
Formatted and consistent issues, with more relevant information to save time and help the maintainers.

## Describe alternatives you've considered
A clear and concise description of the alternative solutions you've considered:
Allow for a standard to develop organically.

## Additional context
N/A

**Comment by carolstran** [comment]
Hey @tesla809 👋 Great idea, thanks for bringing it up! We have issue and PR templates in many of our other repos, but this one must have slipped 🙈 I'll work on it ASAP 😊

**Comment by carolstran** [comment]
👋 @tesla809, just wanted to let you know that this was (finally) addressed and merged 🚀  Thanks again for the suggestion!
