### ISSUE TITLE
Meeshkan tutorial repo deleted. Update README.md for meeshkan/meeshkan

### ISSUE THREAD

**Issue by tesla809** [meeshkan/hmt#195]
### Prerequisites
Follow the initial installation instructions

### Description
The tutorial instructions need to be updated. Now that meeshkan/meeshkan-tutorial is either archived or deleted, the instructions are obsolete and not accurate. Clicking on the link to meeshkan-tutorial result in a 404 error.

Adding in following instructions to go through the tutorial might help clear things up. 

Running:
`meeshkan --help` <- view the options
`meeshkan tutorial` <- start tutorial

### Steps to Reproduce

1. Go thru README.md
2. Follow the instructions in the tutorial section under "Getting started with Meeshkan".
3. Click on the Meeshkan tutorial link
4. Get 404 error.

**Expected behaviour:**
What you expect to happen.
I click on the link in the README.md to go to the tutorial. It takes me to Meeshkan Tutorial. 

**Actual behaviour:**
What actually happens.
I get a 404 error. The repo has been archived or deleted.

**Reproduces how often:**
What percentage of the time does it reproduce?
100% of the time.

### Versions
N/A

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.
None.

**Comment by carolstran** [comment]
👋  Sorry I thought this had been answered. This was fixed with #200 and updated again today with the renaming to `hmt` 🙌 

If you're still having any issues with it, let us know and we'll address it right away!
